"preserve_hierarchy": true

files: [
  {
    "source" : "/EFBChannels/efb-trysh-middleware/efb_trysh_middleware/locale/*.pot",
    "translation" : "/EFBChannels/efb-trysh-middleware/efb_trysh_middleware/locale/%locale_with_underscore%/LC_MESSAGES/%file_name%.po",
  },
]